//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CadenasAnalizadas
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> FechaConsulta { get; set; }
        public string AdnAnalizado { get; set; }
        public string Resultado { get; set; }
    }
}
